// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateGuatemalaIBAN validates Guatemala IBAN
func validateGuatemalaIBAN(iban string) error {
	if len(iban) != 28 {
		return fmt.Errorf("unexpected length, want: 28: %w", ErrValidation)
	}
	if subject := iban[0:2]; subject != "GT" {
		return fmt.Errorf("static value rule, pos: 0, expected value: GT, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 2, length: 2, expected type Digit, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[4:28]; !ascii.IsAlphaNumeric(subject) {
		return fmt.Errorf("range rule, start pos: 4, length: 24, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}
	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}
	return nil
}

// generateGuatemalaIBAN generates Guatemala IBAN
func generateGuatemalaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("GT")
	ascii.Digits(sb, 2)
	ascii.AlphaNumeric(sb, 24)
	return ReplaceChecksum(sb.String())
}

// getGuatemalaBBAN retrieves BBAN structure from Guatemala IBAN
func getGuatemalaBBAN(iban string) (BBAN, error) {
	if len(iban) != 28 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 28: %w", ErrValidation)
	}
	return BBAN{BBAN: iban[4:28], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:28]}, nil
}
