// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateAndorraIBAN validates Andorra IBAN
func validateAndorraIBAN(iban string) error {
	if len(iban) != 24 {
		return &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "AD" {
		return &ErrValidationStaticValue{Position: 0, Expected: "AD", Actual: subject}
	}
	if subject := iban[2:12]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 10, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[12:24]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 12, Length: 12, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateAndorraIBAN generates Andorra IBAN
func generateAndorraIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("AD")
	ascii.Digits(sb, 10)
	ascii.AlphaNumeric(sb, 12)
	return ReplaceChecksum(sb.String())
}

// getAndorraBBAN retrieves BBAN structure from Andorra IBAN
func getAndorraBBAN(iban string) (BBAN, error) {
	if len(iban) != 24 {
		return BBAN{}, &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:24], BankCode: iban[4:8], BranchCode: iban[8:12], AccountNumber: iban[12:24]}, nil
}
