// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateFalklandIslandsIBAN validates Falkland Islands IBAN
func validateFalklandIslandsIBAN(iban string) error {
	if len(iban) != 18 {
		return &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "FK" {
		return &ErrValidationStaticValue{Position: 0, Expected: "FK", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:6]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 2, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[6:18]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 6, Length: 12, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateFalklandIslandsIBAN generates Falkland Islands IBAN
func generateFalklandIslandsIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("FK")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 2)
	ascii.Digits(sb, 12)
	return ReplaceChecksum(sb.String())
}
// getFalklandIslandsBBAN retrieves BBAN structure from Falkland Islands IBAN
func getFalklandIslandsBBAN(iban string) (BBAN, error) {
	if len(iban) != 18 {
		return BBAN{}, &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:18], BankCode: iban[4:6], BranchCode: "", NationalChecksum: "", AccountNumber: iban[6:18]}, nil
}
