// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateGeorgiaIBAN validates Georgia IBAN
func validateGeorgiaIBAN(iban string) error {
	if len(iban) != 22 {
		return fmt.Errorf("unexpected length, want: 22: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "GE" {
		return fmt.Errorf("static value rule, pos: 0, expected value: GE, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:4]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 2, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[4:6]; !ascii.Every(subject, ascii.IsUpperCaseLetter) {
		return fmt.Errorf("range rule, start pos: 4, length: 2, expected type UpperCaseLetters, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[6:22]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 6, length: 16, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateGeorgiaIBAN generates Georgia IBAN
func generateGeorgiaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("GE")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 2)
	ascii.Digits(sb, 16)

	return ReplaceChecksum(sb.String())
}

// getGeorgiaBBAN retrieves BBAN structure from Georgia IBAN
func getGeorgiaBBAN(iban string) (BBAN, error) {
	if len(iban) != 22 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 22: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:22],
		BankCode:         iban[4:6],
		BranchCode:       "",
		NationalChecksum: "",
		AccountNumber:    iban[6:22],
	}, nil
}
