// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateSudanIBAN validates Sudan IBAN
func validateSudanIBAN(iban string) error {
	if len(iban) != 18 {
		return fmt.Errorf("unexpected length, want: 18: %w", ErrValidation)
	}
	if subject := iban[0:2]; subject != "SD" {
		return fmt.Errorf("static value rule, pos: 0, expected value: SD, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[2:18]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 2, length: 16, expected type Digit, found %s: %w", subject, ErrValidation)
	}
	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}
	return nil
}

// generateSudanIBAN generates Sudan IBAN
func generateSudanIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("SD")
	ascii.Digits(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getSudanBBAN retrieves BBAN structure from Sudan IBAN
func getSudanBBAN(iban string) (BBAN, error) {
	if len(iban) != 18 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 18: %w", ErrValidation)
	}
	return BBAN{BBAN: iban[4:18], BankCode: iban[4:6], BranchCode: "", NationalChecksum: "", AccountNumber: iban[6:18]}, nil
}
