// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateGreenlandIBAN validates Greenland IBAN
func validateGreenlandIBAN(iban string) error {
	if len(iban) != 18 {
		return &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "GL" {
		return &ErrValidationStaticValue{Position: 0, Expected: "GL", Actual: subject}
	}
	if subject := iban[2:18]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 16, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateGreenlandIBAN generates Greenland IBAN
func generateGreenlandIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("GL")
	ascii.Digits(sb, 16)
	return ReplaceChecksum(sb.String())
}
// getGreenlandBBAN retrieves BBAN structure from Greenland IBAN
func getGreenlandBBAN(iban string) (BBAN, error) {
	if len(iban) != 18 {
		return BBAN{}, &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:18], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:18]}, nil
}
