// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateLibyaIBAN validates Libya IBAN
func validateLibyaIBAN(iban string) error {
	if len(iban) != 25 {
		return &ErrValidationLength{Expected: 25, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "LY" {
		return &ErrValidationStaticValue{Position: 0, Expected: "LY", Actual: subject}
	}
	if subject := iban[2:25]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 23, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateLibyaIBAN generates Libya IBAN
func generateLibyaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("LY")
	ascii.Digits(sb, 23)
	return ReplaceChecksum(sb.String())
}

// getLibyaBBAN retrieves BBAN structure from Libya IBAN
func getLibyaBBAN(iban string) (BBAN, error) {
	if len(iban) != 25 {
		return BBAN{}, &ErrValidationLength{Expected: 25, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:25], BankCode: iban[4:7], BranchCode: iban[7:10], AccountNumber: iban[10:25]}, nil
}
