// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateTurkeyIBAN validates Turkey IBAN
func validateTurkeyIBAN(iban string) error {
	if len(iban) != 26 {
		return &ErrValidationLength{Expected: 26, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "TR" {
		return &ErrValidationStaticValue{Position: 0, Expected: "TR", Actual: subject}
	}
	if subject := iban[2:10]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 8, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[10:26]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 10, Length: 16, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateTurkeyIBAN generates Turkey IBAN
func generateTurkeyIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("TR")
	ascii.Digits(sb, 8)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}
// getTurkeyBBAN retrieves BBAN structure from Turkey IBAN
func getTurkeyBBAN(iban string) (BBAN, error) {
	if len(iban) != 26 {
		return BBAN{}, &ErrValidationLength{Expected: 26, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:26], BankCode: iban[4:9], BranchCode: "", NationalChecksum: iban[9:10], AccountNumber: iban[10:26]}, nil
}
