// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"

	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateAlbaniaIBAN validates Albania IBAN
func validateAlbaniaIBAN(iban string) error {
	if len(iban) != 28 {
		return fmt.Errorf("unexpected length, want: 28: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "AL" {
		return fmt.Errorf("static value rule, pos: 0, expected value: AL, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:12]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 10, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[12:28]; !ascii.Every(subject, ascii.IsAlphaNumeric) {
		return fmt.Errorf("range rule, start pos: 12, length: 16, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}

	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateAlbaniaIBAN generates Albania IBAN
func generateAlbaniaIBAN() string {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("AL")
	generator.Digits(sb, 10)
	generator.AlphaNumeric(sb, 16)

	return replaceChecksum(sb.String())
}

// getAlbaniaBBAN retrieves BBAN structure from Albania IBAN
func getAlbaniaBBAN(iban string) (BBAN, error) {
	if len(iban) != 28 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 28: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:28],
		BankCode:         iban[4:7],
		BranchCode:       iban[7:11],
		NationalChecksum: iban[11:12],
		AccountNumber:    iban[12:28],
	}, nil
}
