// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateIsraelIBAN validates Israel IBAN
func validateIsraelIBAN(iban string) error {
	if len(iban) != 23 {
		return &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "IL" {
		return &ErrValidationStaticValue{Position: 0, Expected: "IL", Actual: subject}
	}
	if subject := iban[2:23]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 21, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateIsraelIBAN generates Israel IBAN
func generateIsraelIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("IL")
	ascii.Digits(sb, 21)
	return ReplaceChecksum(sb.String())
}

// getIsraelBBAN retrieves BBAN structure from Israel IBAN
func getIsraelBBAN(iban string) (BBAN, error) {
	if len(iban) != 23 {
		return BBAN{}, &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:23], BankCode: iban[4:7], BranchCode: iban[7:10], AccountNumber: iban[10:23]}, nil
}
