// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateBelarusIBAN validates Belarus IBAN
func validateBelarusIBAN(iban string) error {
	if len(iban) != 28 {
		return &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "BY" {
		return &ErrValidationStaticValue{Position: 0, Expected: "BY", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if subject := iban[8:12]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 4, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[12:28]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 12, Length: 16, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateBelarusIBAN generates Belarus IBAN
func generateBelarusIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("BY")
	ascii.Digits(sb, 2)
	ascii.AlphaNumeric(sb, 4)
	ascii.Digits(sb, 4)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getBelarusBBAN retrieves BBAN structure from Belarus IBAN
func getBelarusBBAN(iban string) (BBAN, error) {
	if len(iban) != 28 {
		return BBAN{}, &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:28], BankCode: iban[4:8], BranchCode: "", AccountNumber: iban[8:28]}, nil
}
