// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"
	"strings"

	"github.com/jacoelho/banking/ascii"
)

// ValidateGreenlandIBAN validates Greenland IBAN
func ValidateGreenlandIBAN(iban string) error {
	if len(iban) != 18 {
		return fmt.Errorf("unexpected length, want: 18: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "GL" {
		return fmt.Errorf("static value rule, pos: 0, expected value: GL, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:18]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 16, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateGreenlandIBAN generates Greenland IBAN
func GenerateGreenlandIBAN() string {
	var sb = new(strings.Builder)

	sb.WriteString("GL")
	generator.Digits(sb, 16)

	return ReplaceChecksum(sb.String())
}
