// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateSaoTomeandPrincipeIBAN validates Sao Tome and Principe IBAN
func validateSaoTomeandPrincipeIBAN(iban string) error {
	if len(iban) != 25 {
		return &ErrValidationLength{Expected: 25, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "ST" {
		return &ErrValidationStaticValue{Position: 0, Expected: "ST", Actual: subject}
	}
	if subject := iban[2:25]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 23, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateSaoTomeandPrincipeIBAN generates Sao Tome and Principe IBAN
func generateSaoTomeandPrincipeIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("ST")
	ascii.Digits(sb, 23)
	return ReplaceChecksum(sb.String())
}

// getSaoTomeandPrincipeBBAN retrieves BBAN structure from Sao Tome and Principe IBAN
func getSaoTomeandPrincipeBBAN(iban string) (BBAN, error) {
	if len(iban) != 25 {
		return BBAN{}, &ErrValidationLength{Expected: 25, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:25], BankCode: iban[4:8], BranchCode: iban[8:12], AccountNumber: iban[12:25]}, nil
}
