// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateDominicanRepublicIBAN validates Dominican Republic IBAN
func validateDominicanRepublicIBAN(iban string) error {
	if len(iban) != 28 {
		return &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "DO" {
		return &ErrValidationStaticValue{Position: 0, Expected: "DO", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if subject := iban[8:28]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 20, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateDominicanRepublicIBAN generates Dominican Republic IBAN
func generateDominicanRepublicIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("DO")
	ascii.Digits(sb, 2)
	ascii.AlphaNumeric(sb, 4)
	ascii.Digits(sb, 20)
	return ReplaceChecksum(sb.String())
}
// getDominicanRepublicBBAN retrieves BBAN structure from Dominican Republic IBAN
func getDominicanRepublicBBAN(iban string) (BBAN, error) {
	if len(iban) != 28 {
		return BBAN{}, &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:28], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:28]}, nil
}
