// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateSeychellesIBAN validates Seychelles IBAN
func validateSeychellesIBAN(iban string) error {
	if len(iban) != 31 {
		return &ErrValidationLength{Expected: 31, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "SC" {
		return &ErrValidationStaticValue{Position: 0, Expected: "SC", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:28]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 20, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[28:31]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 28, Length: 3, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateSeychellesIBAN generates Seychelles IBAN
func generateSeychellesIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("SC")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.Digits(sb, 20)
	ascii.UpperCaseLetters(sb, 3)
	return ReplaceChecksum(sb.String())
}
// getSeychellesBBAN retrieves BBAN structure from Seychelles IBAN
func getSeychellesBBAN(iban string) (BBAN, error) {
	if len(iban) != 31 {
		return BBAN{}, &ErrValidationLength{Expected: 31, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:31], BankCode: iban[4:8], BranchCode: iban[8:12], NationalChecksum: "", AccountNumber: iban[12:31]}, nil
}
