// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateSaintLuciaIBAN validates Saint Lucia IBAN
func validateSaintLuciaIBAN(iban string) error {
	if len(iban) != 32 {
		return &ErrValidationLength{Expected: 32, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "LC" {
		return &ErrValidationStaticValue{Position: 0, Expected: "LC", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:32]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 8, Length: 24, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateSaintLuciaIBAN generates Saint Lucia IBAN
func generateSaintLuciaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("LC")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.AlphaNumeric(sb, 24)
	return ReplaceChecksum(sb.String())
}
// getSaintLuciaBBAN retrieves BBAN structure from Saint Lucia IBAN
func getSaintLuciaBBAN(iban string) (BBAN, error) {
	if len(iban) != 32 {
		return BBAN{}, &ErrValidationLength{Expected: 32, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:32], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:32]}, nil
}
