// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateOmanIBAN validates Oman IBAN
func validateOmanIBAN(iban string) error {
	if len(iban) != 23 {
		return fmt.Errorf("unexpected length, want: 23: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "OM" {
		return fmt.Errorf("static value rule, pos: 0, expected value: OM, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:7]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 2, length: 5, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[7:23]; !ascii.IsAlphaNumeric(subject) {
		return fmt.Errorf("range rule, start pos: 7, length: 16, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}

	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateOmanIBAN generates Oman IBAN
func generateOmanIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("OM")
	ascii.Digits(sb, 5)
	ascii.AlphaNumeric(sb, 16)

	return ReplaceChecksum(sb.String())
}

// getOmanBBAN retrieves BBAN structure from Oman IBAN
func getOmanBBAN(iban string) (BBAN, error) {
	if len(iban) != 23 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 23: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:23],
		BankCode:         iban[4:7],
		BranchCode:       "",
		NationalChecksum: "",
		AccountNumber:    iban[7:23],
	}, nil
}
