// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateLibyaIBAN validates Libya IBAN
func validateLibyaIBAN(iban string) error {
	if len(iban) != 25 {
		return fmt.Errorf("unexpected length, want: 25: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "LY" {
		return fmt.Errorf("static value rule, pos: 0, expected value: LY, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:25]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 23, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateLibyaIBAN generates Libya IBAN
func generateLibyaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("LY")
	ascii.Digits(sb, 23)

	return ReplaceChecksum(sb.String())
}

// getLibyaBBAN retrieves BBAN structure from Libya IBAN
func getLibyaBBAN(iban string) (BBAN, error) {
	if len(iban) != 25 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 25: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:25],
		BankCode:         iban[4:7],
		BranchCode:       iban[7:10],
		NationalChecksum: "",
		AccountNumber:    iban[10:25],
	}, nil
}
