// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateTimorLesteIBAN validates Timor Leste IBAN
func validateTimorLesteIBAN(iban string) error {
	if len(iban) != 23 {
		return &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "TL" {
		return &ErrValidationStaticValue{Position: 0, Expected: "TL", Actual: subject}
	}
	if subject := iban[2:23]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 21, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateTimorLesteIBAN generates Timor Leste IBAN
func generateTimorLesteIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("TL")
	ascii.Digits(sb, 21)
	return ReplaceChecksum(sb.String())
}

// getTimorLesteBBAN retrieves BBAN structure from Timor Leste IBAN
func getTimorLesteBBAN(iban string) (BBAN, error) {
	if len(iban) != 23 {
		return BBAN{}, &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:23], BankCode: iban[4:7], BranchCode: "", AccountNumber: iban[7:23]}, nil
}
