// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateLithuaniaIBAN validates Lithuania IBAN
func validateLithuaniaIBAN(iban string) error {
	if len(iban) != 20 {
		return &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "LT" {
		return &ErrValidationStaticValue{Position: 0, Expected: "LT", Actual: subject}
	}
	if subject := iban[2:20]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 18, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateLithuaniaIBAN generates Lithuania IBAN
func generateLithuaniaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("LT")
	ascii.Digits(sb, 18)
	return ReplaceChecksum(sb.String())
}
// getLithuaniaBBAN retrieves BBAN structure from Lithuania IBAN
func getLithuaniaBBAN(iban string) (BBAN, error) {
	if len(iban) != 20 {
		return BBAN{}, &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:20], BankCode: iban[4:9], BranchCode: "", NationalChecksum: "", AccountNumber: iban[9:20]}, nil
}
