// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateSaudiArabiaIBAN validates Saudi Arabia IBAN
func validateSaudiArabiaIBAN(iban string) error {
	if len(iban) != 24 {
		return &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "SA" {
		return &ErrValidationStaticValue{Position: 0, Expected: "SA", Actual: subject}
	}
	if subject := iban[2:6]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 4, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[6:24]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 6, Length: 18, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateSaudiArabiaIBAN generates Saudi Arabia IBAN
func generateSaudiArabiaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("SA")
	ascii.Digits(sb, 4)
	ascii.AlphaNumeric(sb, 18)
	return ReplaceChecksum(sb.String())
}

// getSaudiArabiaBBAN retrieves BBAN structure from Saudi Arabia IBAN
func getSaudiArabiaBBAN(iban string) (BBAN, error) {
	if len(iban) != 24 {
		return BBAN{}, &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:24], BankCode: iban[4:6], BranchCode: "", AccountNumber: iban[6:24]}, nil
}
