// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateFaroeIslandsIBAN validates Faroe Islands IBAN
func validateFaroeIslandsIBAN(iban string) error {
	if len(iban) != 18 {
		return &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "FO" {
		return &ErrValidationStaticValue{Position: 0, Expected: "FO", Actual: subject}
	}
	if subject := iban[2:18]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 16, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateFaroeIslandsIBAN generates Faroe Islands IBAN
func generateFaroeIslandsIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("FO")
	ascii.Digits(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getFaroeIslandsBBAN retrieves BBAN structure from Faroe Islands IBAN
func getFaroeIslandsBBAN(iban string) (BBAN, error) {
	if len(iban) != 18 {
		return BBAN{}, &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:18], BankCode: iban[4:8], BranchCode: "", AccountNumber: iban[8:18]}, nil
}
