// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateTurkiyeIBAN validates Turkiye IBAN
func validateTurkiyeIBAN(iban string) error {
	if len(iban) != 26 {
		return &ErrValidationLength{Expected: 26, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "TR" {
		return &ErrValidationStaticValue{Position: 0, Expected: "TR", Actual: subject}
	}
	if subject := iban[2:10]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 8, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[10:26]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 10, Length: 16, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateTurkiyeIBAN generates Turkiye IBAN
func generateTurkiyeIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("TR")
	ascii.Digits(sb, 8)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getTurkiyeBBAN retrieves BBAN structure from Turkiye IBAN
func getTurkiyeBBAN(iban string) (BBAN, error) {
	if len(iban) != 26 {
		return BBAN{}, &ErrValidationLength{Expected: 26, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:26], BankCode: iban[4:9], BranchCode: "", AccountNumber: iban[9:26]}, nil
}
