// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateCostaRicaIBAN validates Costa Rica IBAN
func validateCostaRicaIBAN(iban string) error {
	if len(iban) != 22 {
		return &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "CR" {
		return &ErrValidationStaticValue{Position: 0, Expected: "CR", Actual: subject}
	}
	if subject := iban[2:22]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 20, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateCostaRicaIBAN generates Costa Rica IBAN
func generateCostaRicaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("CR")
	ascii.Digits(sb, 20)
	return ReplaceChecksum(sb.String())
}
// getCostaRicaBBAN retrieves BBAN structure from Costa Rica IBAN
func getCostaRicaBBAN(iban string) (BBAN, error) {
	if len(iban) != 22 {
		return BBAN{}, &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:22], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:22]}, nil
}
