// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateStateOfPalestineIBAN validates State Of Palestine IBAN
func validateStateOfPalestineIBAN(iban string) error {
	if len(iban) != 29 {
		return &ErrValidationLength{Expected: 29, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "PS" {
		return &ErrValidationStaticValue{Position: 0, Expected: "PS", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:29]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 8, Length: 21, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateStateOfPalestineIBAN generates State Of Palestine IBAN
func generateStateOfPalestineIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("PS")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.AlphaNumeric(sb, 21)
	return ReplaceChecksum(sb.String())
}
// getStateOfPalestineBBAN retrieves BBAN structure from State Of Palestine IBAN
func getStateOfPalestineBBAN(iban string) (BBAN, error) {
	if len(iban) != 29 {
		return BBAN{}, &ErrValidationLength{Expected: 29, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:29], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:29]}, nil
}
