// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateGeorgiaIBAN validates Georgia IBAN
func validateGeorgiaIBAN(iban string) error {
	if len(iban) != 22 {
		return &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "GE" {
		return &ErrValidationStaticValue{Position: 0, Expected: "GE", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:6]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 2, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[6:22]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 6, Length: 16, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateGeorgiaIBAN generates Georgia IBAN
func generateGeorgiaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("GE")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 2)
	ascii.Digits(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getGeorgiaBBAN retrieves BBAN structure from Georgia IBAN
func getGeorgiaBBAN(iban string) (BBAN, error) {
	if len(iban) != 22 {
		return BBAN{}, &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:22], BankCode: iban[4:6], BranchCode: "", AccountNumber: iban[6:22]}, nil
}
