// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateGermanyIBAN validates Germany IBAN
func validateGermanyIBAN(iban string) error {
	if len(iban) != 22 {
		return &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "DE" {
		return &ErrValidationStaticValue{Position: 0, Expected: "DE", Actual: subject}
	}
	if subject := iban[2:22]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 20, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateGermanyIBAN generates Germany IBAN
func generateGermanyIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("DE")
	ascii.Digits(sb, 20)
	return ReplaceChecksum(sb.String())
}

// getGermanyBBAN retrieves BBAN structure from Germany IBAN
func getGermanyBBAN(iban string) (BBAN, error) {
	if len(iban) != 22 {
		return BBAN{}, &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:22], BankCode: iban[4:12], BranchCode: "", AccountNumber: iban[12:22]}, nil
}
