// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateMauritiusIBAN validates Mauritius IBAN
func validateMauritiusIBAN(iban string) error {
	if len(iban) != 30 {
		return &ErrValidationLength{Expected: 30, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "MU" {
		return &ErrValidationStaticValue{Position: 0, Expected: "MU", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:27]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 19, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[27:30]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 27, Length: 3, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateMauritiusIBAN generates Mauritius IBAN
func generateMauritiusIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("MU")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.Digits(sb, 19)
	ascii.UpperCaseLetters(sb, 3)
	return ReplaceChecksum(sb.String())
}

// getMauritiusBBAN retrieves BBAN structure from Mauritius IBAN
func getMauritiusBBAN(iban string) (BBAN, error) {
	if len(iban) != 30 {
		return BBAN{}, &ErrValidationLength{Expected: 30, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:30], BankCode: iban[4:10], BranchCode: iban[10:12], AccountNumber: iban[12:30]}, nil
}
