// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"

	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// ValidateStateOfPalestineIBAN validates State Of Palestine IBAN
func ValidateStateOfPalestineIBAN(iban string) error {
	if len(iban) != 29 {
		return fmt.Errorf("unexpected length, want: 29: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "PS" {
		return fmt.Errorf("static value rule, pos: 0, expected value: PS, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:4]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 2, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[4:8]; !ascii.Every(subject, ascii.IsUpperCaseLetter) {
		return fmt.Errorf("range rule, start pos: 4, length: 4, expected type UpperCaseLetters, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[8:29]; !ascii.Every(subject, ascii.IsAlphaNumeric) {
		return fmt.Errorf("range rule, start pos: 8, length: 21, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateStateOfPalestineIBAN generates State Of Palestine IBAN
func GenerateStateOfPalestineIBAN() string {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("PS")
	generator.Digits(sb, 2)
	generator.UpperCaseLetters(sb, 4)
	generator.AlphaNumeric(sb, 21)

	return ReplaceChecksum(sb.String())
}

// GetStateOfPalestineBBAN retrieves BBAN structure from State Of Palestine IBAN
func GetStateOfPalestineBBAN(iban string) (BBAN, error) {
	if len(iban) != 29 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 29: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:29],
		BankCode:         iban[4:8],
		BranchCode:       "",
		NationalChecksum: "",
		AccountNumber:    iban[8:29],
	}, nil
}
