// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateStateOfPalestineIBAN validates State Of Palestine IBAN
func validateStateOfPalestineIBAN(iban string) error {
	if len(iban) != 29 {
		return fmt.Errorf("unexpected length, want: 29: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "PS" {
		return fmt.Errorf("static value rule, pos: 0, expected value: PS, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 2, length: 2, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return fmt.Errorf("range rule, start pos: 4, length: 4, expected type UpperCaseLetters, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[8:29]; !ascii.IsAlphaNumeric(subject) {
		return fmt.Errorf("range rule, start pos: 8, length: 21, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}

	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateStateOfPalestineIBAN generates State Of Palestine IBAN
func generateStateOfPalestineIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("PS")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.AlphaNumeric(sb, 21)

	return ReplaceChecksum(sb.String())
}

// getStateOfPalestineBBAN retrieves BBAN structure from State Of Palestine IBAN
func getStateOfPalestineBBAN(iban string) (BBAN, error) {
	if len(iban) != 29 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 29: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:29],
		BankCode:         iban[4:8],
		BranchCode:       "",
		NationalChecksum: "",
		AccountNumber:    iban[8:29],
	}, nil
}
