// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateKazakhstanIBAN validates Kazakhstan IBAN
func validateKazakhstanIBAN(iban string) error {
	if len(iban) != 20 {
		return &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "KZ" {
		return &ErrValidationStaticValue{Position: 0, Expected: "KZ", Actual: subject}
	}
	if subject := iban[2:7]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 5, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[7:20]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 7, Length: 13, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateKazakhstanIBAN generates Kazakhstan IBAN
func generateKazakhstanIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("KZ")
	ascii.Digits(sb, 5)
	ascii.AlphaNumeric(sb, 13)
	return ReplaceChecksum(sb.String())
}

// getKazakhstanBBAN retrieves BBAN structure from Kazakhstan IBAN
func getKazakhstanBBAN(iban string) (BBAN, error) {
	if len(iban) != 20 {
		return BBAN{}, &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:20], BankCode: iban[4:7], BranchCode: "", AccountNumber: iban[7:20]}, nil
}
