// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateTunisiaIBAN validates Tunisia IBAN
func validateTunisiaIBAN(iban string) error {
	if len(iban) != 24 {
		return &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "TN" {
		return &ErrValidationStaticValue{Position: 0, Expected: "TN", Actual: subject}
	}
	if subject := iban[2:24]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 22, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateTunisiaIBAN generates Tunisia IBAN
func generateTunisiaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("TN")
	ascii.Digits(sb, 22)
	return ReplaceChecksum(sb.String())
}

// getTunisiaBBAN retrieves BBAN structure from Tunisia IBAN
func getTunisiaBBAN(iban string) (BBAN, error) {
	if len(iban) != 24 {
		return BBAN{}, &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:24], BankCode: iban[4:6], BranchCode: iban[6:9], AccountNumber: iban[9:24]}, nil
}
