// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateMauritaniaIBAN validates Mauritania IBAN
func validateMauritaniaIBAN(iban string) error {
	if len(iban) != 27 {
		return &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "MR" {
		return &ErrValidationStaticValue{Position: 0, Expected: "MR", Actual: subject}
	}
	if subject := iban[2:27]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 25, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateMauritaniaIBAN generates Mauritania IBAN
func generateMauritaniaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("MR")
	ascii.Digits(sb, 25)
	return ReplaceChecksum(sb.String())
}
// getMauritaniaBBAN retrieves BBAN structure from Mauritania IBAN
func getMauritaniaBBAN(iban string) (BBAN, error) {
	if len(iban) != 27 {
		return BBAN{}, &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:27], BankCode: iban[4:9], BranchCode: iban[9:14], NationalChecksum: iban[25:27], AccountNumber: iban[14:25]}, nil
}
