// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateKosovoIBAN validates Kosovo IBAN
func validateKosovoIBAN(iban string) error {
	if len(iban) != 20 {
		return &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "XK" {
		return &ErrValidationStaticValue{Position: 0, Expected: "XK", Actual: subject}
	}
	if subject := iban[2:20]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 18, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateKosovoIBAN generates Kosovo IBAN
func generateKosovoIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("XK")
	ascii.Digits(sb, 18)
	return ReplaceChecksum(sb.String())
}

// getKosovoBBAN retrieves BBAN structure from Kosovo IBAN
func getKosovoBBAN(iban string) (BBAN, error) {
	if len(iban) != 20 {
		return BBAN{}, &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:20], BankCode: iban[4:6], BranchCode: iban[6:8], AccountNumber: iban[8:20]}, nil
}
