// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"
	"strings"

	"github.com/jacoelho/banking/ascii"
)

// ValidateIcelandIBAN validates Iceland IBAN
func ValidateIcelandIBAN(iban string) error {
	if len(iban) != 26 {
		return fmt.Errorf("unexpected length, want: 26: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "IS" {
		return fmt.Errorf("static value rule, pos: 0, expected value: IS, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:26]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 24, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateIcelandIBAN generates Iceland IBAN
func GenerateIcelandIBAN() string {
	var sb = new(strings.Builder)

	sb.WriteString("IS")
	generator.Digits(sb, 24)

	return ReplaceChecksum(sb.String())
}
