// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateLiechtensteinIBAN validates Liechtenstein IBAN
func validateLiechtensteinIBAN(iban string) error {
	if len(iban) != 21 {
		return &ErrValidationLength{Expected: 21, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "LI" {
		return &ErrValidationStaticValue{Position: 0, Expected: "LI", Actual: subject}
	}
	if subject := iban[2:9]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 7, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[9:21]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 9, Length: 12, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateLiechtensteinIBAN generates Liechtenstein IBAN
func generateLiechtensteinIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("LI")
	ascii.Digits(sb, 7)
	ascii.AlphaNumeric(sb, 12)
	return ReplaceChecksum(sb.String())
}

// getLiechtensteinBBAN retrieves BBAN structure from Liechtenstein IBAN
func getLiechtensteinBBAN(iban string) (BBAN, error) {
	if len(iban) != 21 {
		return BBAN{}, &ErrValidationLength{Expected: 21, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:21], BankCode: iban[4:9], BranchCode: "", AccountNumber: iban[9:21]}, nil
}
