// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateGreeceIBAN validates Greece IBAN
func validateGreeceIBAN(iban string) error {
	if len(iban) != 27 {
		return fmt.Errorf("unexpected length, want: 27: %w", ErrValidation)
	}
	if subject := iban[0:2]; subject != "GR" {
		return fmt.Errorf("static value rule, pos: 0, expected value: GR, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[2:11]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 2, length: 9, expected type Digit, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[11:27]; !ascii.IsAlphaNumeric(subject) {
		return fmt.Errorf("range rule, start pos: 11, length: 16, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}
	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}
	return nil
}

// generateGreeceIBAN generates Greece IBAN
func generateGreeceIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("GR")
	ascii.Digits(sb, 9)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getGreeceBBAN retrieves BBAN structure from Greece IBAN
func getGreeceBBAN(iban string) (BBAN, error) {
	if len(iban) != 27 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 27: %w", ErrValidation)
	}
	return BBAN{BBAN: iban[4:27], BankCode: iban[4:7], BranchCode: iban[7:11], NationalChecksum: "", AccountNumber: iban[11:27]}, nil
}
