// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateSloveniaIBAN validates Slovenia IBAN
func validateSloveniaIBAN(iban string) error {
	if len(iban) != 19 {
		return fmt.Errorf("unexpected length, want: 19: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "SI" {
		return fmt.Errorf("static value rule, pos: 0, expected value: SI, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:19]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 17, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateSloveniaIBAN generates Slovenia IBAN
func generateSloveniaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("SI")
	ascii.Digits(sb, 17)

	return ReplaceChecksum(sb.String())
}

// getSloveniaBBAN retrieves BBAN structure from Slovenia IBAN
func getSloveniaBBAN(iban string) (BBAN, error) {
	if len(iban) != 19 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 19: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:19],
		BankCode:         iban[4:6],
		BranchCode:       iban[6:9],
		NationalChecksum: iban[15:19],
		AccountNumber:    iban[9:15],
	}, nil
}
