// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateIrelandIBAN validates Ireland IBAN
func validateIrelandIBAN(iban string) error {
	if len(iban) != 22 {
		return &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "IE" {
		return &ErrValidationStaticValue{Position: 0, Expected: "IE", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:22]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 14, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateIrelandIBAN generates Ireland IBAN
func generateIrelandIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("IE")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.Digits(sb, 14)
	return ReplaceChecksum(sb.String())
}
// getIrelandBBAN retrieves BBAN structure from Ireland IBAN
func getIrelandBBAN(iban string) (BBAN, error) {
	if len(iban) != 22 {
		return BBAN{}, &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:22], BankCode: iban[4:8], BranchCode: iban[8:14], NationalChecksum: "", AccountNumber: iban[14:22]}, nil
}
