// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateCyprusIBAN validates Cyprus IBAN
func validateCyprusIBAN(iban string) error {
	if len(iban) != 28 {
		return &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "CY" {
		return &ErrValidationStaticValue{Position: 0, Expected: "CY", Actual: subject}
	}
	if subject := iban[2:12]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 10, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[12:28]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 12, Length: 16, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateCyprusIBAN generates Cyprus IBAN
func generateCyprusIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("CY")
	ascii.Digits(sb, 10)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getCyprusBBAN retrieves BBAN structure from Cyprus IBAN
func getCyprusBBAN(iban string) (BBAN, error) {
	if len(iban) != 28 {
		return BBAN{}, &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:28], BankCode: iban[4:7], BranchCode: iban[7:12], AccountNumber: iban[12:28]}, nil
}
