// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"
	"strings"

	"github.com/jacoelho/banking/ascii"
)

// ValidateBelgiumIBAN validates Belgium IBAN
func ValidateBelgiumIBAN(iban string) error {
	if len(iban) != 16 {
		return fmt.Errorf("unexpected length, want: 16: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "BE" {
		return fmt.Errorf("static value rule, pos: 0, expected value: BE, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:16]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 14, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateBelgiumIBAN generates Belgium IBAN
func GenerateBelgiumIBAN() string {
	var sb = new(strings.Builder)

	sb.WriteString("BE")
	generator.Digits(sb, 14)

	return ReplaceChecksum(sb.String())
}
