// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateJordanIBAN validates Jordan IBAN
func validateJordanIBAN(iban string) error {
	if len(iban) != 30 {
		return &ErrValidationLength{Expected: 30, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "JO" {
		return &ErrValidationStaticValue{Position: 0, Expected: "JO", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:12]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 4, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[12:30]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 12, Length: 18, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateJordanIBAN generates Jordan IBAN
func generateJordanIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("JO")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.Digits(sb, 4)
	ascii.AlphaNumeric(sb, 18)
	return ReplaceChecksum(sb.String())
}
// getJordanBBAN retrieves BBAN structure from Jordan IBAN
func getJordanBBAN(iban string) (BBAN, error) {
	if len(iban) != 30 {
		return BBAN{}, &ErrValidationLength{Expected: 30, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:30], BankCode: iban[4:8], BranchCode: iban[8:12], NationalChecksum: "", AccountNumber: iban[12:30]}, nil
}
