// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"
	"strings"

	"github.com/jacoelho/banking/ascii"
)

// ValidateMauritaniaIBAN validates Mauritania IBAN
func ValidateMauritaniaIBAN(iban string) error {
	if len(iban) != 27 {
		return fmt.Errorf("unexpected length, want: 27: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "MR" {
		return fmt.Errorf("static value rule, pos: 0, expected value: MR, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:27]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 25, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateMauritaniaIBAN generates Mauritania IBAN
func GenerateMauritaniaIBAN() string {
	var sb = new(strings.Builder)

	sb.WriteString("MR")
	generator.Digits(sb, 25)

	return ReplaceChecksum(sb.String())
}
