// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateDjiboutiIBAN validates Djibouti IBAN
func validateDjiboutiIBAN(iban string) error {
	if len(iban) != 27 {
		return &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "DJ" {
		return &ErrValidationStaticValue{Position: 0, Expected: "DJ", Actual: subject}
	}
	if subject := iban[2:27]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 25, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateDjiboutiIBAN generates Djibouti IBAN
func generateDjiboutiIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("DJ")
	ascii.Digits(sb, 25)
	return ReplaceChecksum(sb.String())
}

// getDjiboutiBBAN retrieves BBAN structure from Djibouti IBAN
func getDjiboutiBBAN(iban string) (BBAN, error) {
	if len(iban) != 27 {
		return BBAN{}, &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:27], BankCode: iban[4:9], BranchCode: iban[9:14], AccountNumber: iban[14:27]}, nil
}
