// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"

	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateIsraelIBAN validates Israel IBAN
func validateIsraelIBAN(iban string) error {
	if len(iban) != 23 {
		return fmt.Errorf("unexpected length, want: 23: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "IL" {
		return fmt.Errorf("static value rule, pos: 0, expected value: IL, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:23]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 21, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateIsraelIBAN generates Israel IBAN
func generateIsraelIBAN() string {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("IL")
	ascii.Digits(sb, 21)

	return replaceChecksum(sb.String())
}

// getIsraelBBAN retrieves BBAN structure from Israel IBAN
func getIsraelBBAN(iban string) (BBAN, error) {
	if len(iban) != 23 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 23: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:23],
		BankCode:         iban[4:7],
		BranchCode:       iban[7:10],
		NationalChecksum: "",
		AccountNumber:    iban[10:23],
	}, nil
}
