// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateSanMarinoIBAN validates San Marino IBAN
func validateSanMarinoIBAN(iban string) error {
	if len(iban) != 27 {
		return &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "SM" {
		return &ErrValidationStaticValue{Position: 0, Expected: "SM", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:5]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 1, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[5:15]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 5, Length: 10, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[15:27]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 15, Length: 12, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateSanMarinoIBAN generates San Marino IBAN
func generateSanMarinoIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("SM")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 1)
	ascii.Digits(sb, 10)
	ascii.AlphaNumeric(sb, 12)
	return ReplaceChecksum(sb.String())
}

// getSanMarinoBBAN retrieves BBAN structure from San Marino IBAN
func getSanMarinoBBAN(iban string) (BBAN, error) {
	if len(iban) != 27 {
		return BBAN{}, &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:27], BankCode: iban[5:10], BranchCode: iban[10:15], AccountNumber: iban[15:27]}, nil
}
