// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateSudanIBAN validates Sudan IBAN
func validateSudanIBAN(iban string) error {
	if len(iban) != 18 {
		return &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "SD" {
		return &ErrValidationStaticValue{Position: 0, Expected: "SD", Actual: subject}
	}
	if subject := iban[2:18]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 16, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateSudanIBAN generates Sudan IBAN
func generateSudanIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("SD")
	ascii.Digits(sb, 16)
	return ReplaceChecksum(sb.String())
}
// getSudanBBAN retrieves BBAN structure from Sudan IBAN
func getSudanBBAN(iban string) (BBAN, error) {
	if len(iban) != 18 {
		return BBAN{}, &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:18], BankCode: iban[4:6], BranchCode: "", NationalChecksum: "", AccountNumber: iban[6:18]}, nil
}
