// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateRomaniaIBAN validates Romania IBAN
func validateRomaniaIBAN(iban string) error {
	if len(iban) != 24 {
		return &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "RO" {
		return &ErrValidationStaticValue{Position: 0, Expected: "RO", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:24]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 8, Length: 16, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateRomaniaIBAN generates Romania IBAN
func generateRomaniaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("RO")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}
// getRomaniaBBAN retrieves BBAN structure from Romania IBAN
func getRomaniaBBAN(iban string) (BBAN, error) {
	if len(iban) != 24 {
		return BBAN{}, &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:24], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:24]}, nil
}
