// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateGuatemalaIBAN validates Guatemala IBAN
func validateGuatemalaIBAN(iban string) error {
	if len(iban) != 28 {
		return &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "GT" {
		return &ErrValidationStaticValue{Position: 0, Expected: "GT", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:28]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 4, Length: 24, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateGuatemalaIBAN generates Guatemala IBAN
func generateGuatemalaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("GT")
	ascii.Digits(sb, 2)
	ascii.AlphaNumeric(sb, 24)
	return ReplaceChecksum(sb.String())
}
// getGuatemalaBBAN retrieves BBAN structure from Guatemala IBAN
func getGuatemalaBBAN(iban string) (BBAN, error) {
	if len(iban) != 28 {
		return BBAN{}, &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:28], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:28]}, nil
}
