// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateKingdomOfBahrainIBAN validates Kingdom Of Bahrain IBAN
func validateKingdomOfBahrainIBAN(iban string) error {
	if len(iban) != 22 {
		return fmt.Errorf("unexpected length, want: 22: %w", ErrValidation)
	}
	if subject := iban[0:2]; subject != "BH" {
		return fmt.Errorf("static value rule, pos: 0, expected value: BH, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 2, length: 2, expected type Digit, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return fmt.Errorf("range rule, start pos: 4, length: 4, expected type UpperCaseLetters, found %s: %w", subject, ErrValidation)
	}
	if subject := iban[8:22]; !ascii.IsAlphaNumeric(subject) {
		return fmt.Errorf("range rule, start pos: 8, length: 14, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}
	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}
	return nil
}

// generateKingdomOfBahrainIBAN generates Kingdom Of Bahrain IBAN
func generateKingdomOfBahrainIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("BH")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.AlphaNumeric(sb, 14)
	return ReplaceChecksum(sb.String())
}

// getKingdomOfBahrainBBAN retrieves BBAN structure from Kingdom Of Bahrain IBAN
func getKingdomOfBahrainBBAN(iban string) (BBAN, error) {
	if len(iban) != 22 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 22: %w", ErrValidation)
	}
	return BBAN{BBAN: iban[4:22], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:22]}, nil
}
