// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateSerbiaIBAN validates Serbia IBAN
func validateSerbiaIBAN(iban string) error {
	if len(iban) != 22 {
		return &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "RS" {
		return &ErrValidationStaticValue{Position: 0, Expected: "RS", Actual: subject}
	}
	if subject := iban[2:22]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 20, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateSerbiaIBAN generates Serbia IBAN
func generateSerbiaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("RS")
	ascii.Digits(sb, 20)
	return ReplaceChecksum(sb.String())
}
// getSerbiaBBAN retrieves BBAN structure from Serbia IBAN
func getSerbiaBBAN(iban string) (BBAN, error) {
	if len(iban) != 22 {
		return BBAN{}, &ErrValidationLength{Expected: 22, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:22], BankCode: iban[4:7], BranchCode: "", NationalChecksum: iban[20:22], AccountNumber: iban[7:20]}, nil
}
