// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateUkraineIBAN validates Ukraine IBAN
func validateUkraineIBAN(iban string) error {
	if len(iban) != 29 {
		return &ErrValidationLength{Expected: 29, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "UA" {
		return &ErrValidationStaticValue{Position: 0, Expected: "UA", Actual: subject}
	}
	if subject := iban[2:10]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 8, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[10:29]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 10, Length: 19, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateUkraineIBAN generates Ukraine IBAN
func generateUkraineIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("UA")
	ascii.Digits(sb, 8)
	ascii.AlphaNumeric(sb, 19)
	return ReplaceChecksum(sb.String())
}
// getUkraineBBAN retrieves BBAN structure from Ukraine IBAN
func getUkraineBBAN(iban string) (BBAN, error) {
	if len(iban) != 29 {
		return BBAN{}, &ErrValidationLength{Expected: 29, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:29], BankCode: iban[4:10], BranchCode: "", NationalChecksum: "", AccountNumber: iban[10:29]}, nil
}
