// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"

	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateEgyptIBAN validates Egypt IBAN
func validateEgyptIBAN(iban string) error {
	if len(iban) != 29 {
		return fmt.Errorf("unexpected length, want: 29: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "EG" {
		return fmt.Errorf("static value rule, pos: 0, expected value: EG, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:29]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 27, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateEgyptIBAN generates Egypt IBAN
func generateEgyptIBAN() string {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("EG")
	ascii.Digits(sb, 27)

	return replaceChecksum(sb.String())
}

// getEgyptBBAN retrieves BBAN structure from Egypt IBAN
func getEgyptBBAN(iban string) (BBAN, error) {
	if len(iban) != 29 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 29: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:29],
		BankCode:         iban[4:8],
		BranchCode:       iban[8:12],
		NationalChecksum: "",
		AccountNumber:    iban[12:29],
	}, nil
}
