// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateMoldovaIBAN validates Moldova IBAN
func validateMoldovaIBAN(iban string) error {
	if len(iban) != 24 {
		return &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "MD" {
		return &ErrValidationStaticValue{Position: 0, Expected: "MD", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:24]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 4, Length: 20, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateMoldovaIBAN generates Moldova IBAN
func generateMoldovaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("MD")
	ascii.Digits(sb, 2)
	ascii.AlphaNumeric(sb, 20)
	return ReplaceChecksum(sb.String())
}

// getMoldovaBBAN retrieves BBAN structure from Moldova IBAN
func getMoldovaBBAN(iban string) (BBAN, error) {
	if len(iban) != 24 {
		return BBAN{}, &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:24], BankCode: iban[4:6], BranchCode: "", AccountNumber: iban[6:24]}, nil
}
