// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateIraqIBAN validates Iraq IBAN
func validateIraqIBAN(iban string) error {
	if len(iban) != 23 {
		return &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "IQ" {
		return &ErrValidationStaticValue{Position: 0, Expected: "IQ", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:23]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 15, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateIraqIBAN generates Iraq IBAN
func generateIraqIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("IQ")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.Digits(sb, 15)
	return ReplaceChecksum(sb.String())
}
// getIraqBBAN retrieves BBAN structure from Iraq IBAN
func getIraqBBAN(iban string) (BBAN, error) {
	if len(iban) != 23 {
		return BBAN{}, &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:23], BankCode: iban[4:8], BranchCode: iban[8:11], NationalChecksum: "", AccountNumber: iban[11:23]}, nil
}
