// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateNorwayIBAN validates Norway IBAN
func validateNorwayIBAN(iban string) error {
	if len(iban) != 15 {
		return &ErrValidationLength{Expected: 15, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "NO" {
		return &ErrValidationStaticValue{Position: 0, Expected: "NO", Actual: subject}
	}
	if subject := iban[2:15]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 13, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateNorwayIBAN generates Norway IBAN
func generateNorwayIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("NO")
	ascii.Digits(sb, 13)
	return ReplaceChecksum(sb.String())
}

// getNorwayBBAN retrieves BBAN structure from Norway IBAN
func getNorwayBBAN(iban string) (BBAN, error) {
	if len(iban) != 15 {
		return BBAN{}, &ErrValidationLength{Expected: 15, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:15], BankCode: iban[4:8], BranchCode: "", AccountNumber: iban[8:15]}, nil
}
