// Code generated by banking/registry; DO NOT EDIT.

package iban

const (
	// Country Code Andorra
	ad = "AD"
	// Country Code United Arab Emirates
	ae = "AE"
	// Country Code Albania
	al = "AL"
	// Country Code Austria
	at = "AT"
	// Country Code Republic Of Azerbaijan
	az = "AZ"
	// Country Code Bosnia And Herzegovina
	ba = "BA"
	// Country Code Belgium
	be = "BE"
	// Country Code Bulgaria
	bg = "BG"
	// Country Code Kingdom Of Bahrain
	bh = "BH"
	// Country Code Burundi
	bi = "BI"
	// Country Code Brazil
	br = "BR"
	// Country Code Belarus
	by = "BY"
	// Country Code Switzerland
	ch = "CH"
	// Country Code Costa Rica
	cr = "CR"
	// Country Code Cyprus
	cy = "CY"
	// Country Code Czech Republic
	cz = "CZ"
	// Country Code Germany
	de = "DE"
	// Country Code Djibouti
	dj = "DJ"
	// Country Code Denmark
	dk = "DK"
	// Country Code Dominican Republic
	do = "DO"
	// Country Code Estonia
	ee = "EE"
	// Country Code Egypt
	eg = "EG"
	// Country Code Spain
	es = "ES"
	// Country Code Finland
	fi = "FI"
	// Country Code Faroe Islands
	fo = "FO"
	// Country Code France
	fr = "FR"
	// Country Code United Kingdom
	gb = "GB"
	// Country Code Georgia
	ge = "GE"
	// Country Code Gibraltar
	gi = "GI"
	// Country Code Greenland
	gl = "GL"
	// Country Code Greece
	gr = "GR"
	// Country Code Guatemala
	gt = "GT"
	// Country Code Croatia
	hr = "HR"
	// Country Code Hungary
	hu = "HU"
	// Country Code Ireland
	ie = "IE"
	// Country Code Israel
	il = "IL"
	// Country Code Iraq
	iq = "IQ"
	// Country Code Iceland
	is = "IS"
	// Country Code Italy
	it = "IT"
	// Country Code Jordan
	jo = "JO"
	// Country Code Kuwait
	kw = "KW"
	// Country Code Kazakhstan
	kz = "KZ"
	// Country Code Lebanon
	lb = "LB"
	// Country Code Saint Lucia
	lc = "LC"
	// Country Code Principality Of Liechtenstein
	li = "LI"
	// Country Code Lithuania
	lt = "LT"
	// Country Code Luxembourg
	lu = "LU"
	// Country Code Latvia
	lv = "LV"
	// Country Code Libya
	ly = "LY"
	// Country Code Monaco
	mc = "MC"
	// Country Code Moldova
	md = "MD"
	// Country Code Montenegro
	me = "ME"
	// Country Code Macedonia
	mk = "MK"
	// Country Code Mauritania
	mr = "MR"
	// Country Code Malta
	mt = "MT"
	// Country Code Mauritius
	mu = "MU"
	// Country Code The Netherlands
	nl = "NL"
	// Country Code Norway
	no = "NO"
	// Country Code Pakistan
	pk = "PK"
	// Country Code Poland
	pl = "PL"
	// Country Code State Of Palestine
	ps = "PS"
	// Country Code Portugal
	pt = "PT"
	// Country Code Qatar
	qa = "QA"
	// Country Code Romania
	ro = "RO"
	// Country Code Serbia
	rs = "RS"
	// Country Code Russia
	ru = "RU"
	// Country Code Saudi Arabia
	sa = "SA"
	// Country Code Seychelles
	sc = "SC"
	// Country Code Sudan
	sd = "SD"
	// Country Code Sweden
	se = "SE"
	// Country Code Slovenia
	si = "SI"
	// Country Code Slovak Republic
	sk = "SK"
	// Country Code San Marino
	sm = "SM"
	// Country Code Sao Tome And Principe
	st = "ST"
	// Country Code El Salvador
	sv = "SV"
	// Country Code Timor Leste
	tl = "TL"
	// Country Code Tunisia
	tn = "TN"
	// Country Code Turkey
	tr = "TR"
	// Country Code Ukraine
	ua = "UA"
	// Country Code Vatican City State
	va = "VA"
	// Country Code British Virgin Islands
	vg = "VG"
	// Country Code Republic Of Kosovo
	xk = "XK"
	// Country Code French Guyana
	gf = "GF"
	// Country Code Guadeloupe
	gp = "GP"
	// Country Code Martinique
	mq = "MQ"
	// Country Code Reunion
	re = "RE"
	// Country Code French Polynesia
	fp = "FP"
	// Country Code French Southern Territories
	tf = "TF"
	// Country Code Mayotte
	yt = "YT"
	// Country Code New Caledonia
	nc = "NC"
	// Country Code Saint Barthelemy
	bl = "BL"
	// Country Code Saint Martin
	mf = "MF"
	// Country Code Saint Pierre Et Miquelon
	pm = "PM"
	// Country Code Wallis And Futuna Islands
	wf = "WF"
)
