// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validatePolandIBAN validates Poland IBAN
func validatePolandIBAN(iban string) error {
	if len(iban) != 28 {
		return &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "PL" {
		return &ErrValidationStaticValue{Position: 0, Expected: "PL", Actual: subject}
	}
	if subject := iban[2:28]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 26, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generatePolandIBAN generates Poland IBAN
func generatePolandIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("PL")
	ascii.Digits(sb, 26)
	return ReplaceChecksum(sb.String())
}

// getPolandBBAN retrieves BBAN structure from Poland IBAN
func getPolandBBAN(iban string) (BBAN, error) {
	if len(iban) != 28 {
		return BBAN{}, &ErrValidationLength{Expected: 28, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:28], BankCode: iban[4:12], BranchCode: "", AccountNumber: iban[12:28]}, nil
}
