// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateIcelandIBAN validates Iceland IBAN
func validateIcelandIBAN(iban string) error {
	if len(iban) != 26 {
		return &ErrValidationLength{Expected: 26, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "IS" {
		return &ErrValidationStaticValue{Position: 0, Expected: "IS", Actual: subject}
	}
	if subject := iban[2:26]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 24, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateIcelandIBAN generates Iceland IBAN
func generateIcelandIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("IS")
	ascii.Digits(sb, 24)
	return ReplaceChecksum(sb.String())
}
// getIcelandBBAN retrieves BBAN structure from Iceland IBAN
func getIcelandBBAN(iban string) (BBAN, error) {
	if len(iban) != 26 {
		return BBAN{}, &ErrValidationLength{Expected: 26, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:26], BankCode: iban[4:8], BranchCode: iban[10:16], NationalChecksum: "", AccountNumber: iban[16:26]}, nil
}
