// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateNetherlandsIBAN validates Netherlands IBAN
func validateNetherlandsIBAN(iban string) error {
	if len(iban) != 18 {
		return &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "NL" {
		return &ErrValidationStaticValue{Position: 0, Expected: "NL", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:18]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 8, Length: 10, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateNetherlandsIBAN generates Netherlands IBAN
func generateNetherlandsIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("NL")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.Digits(sb, 10)
	return ReplaceChecksum(sb.String())
}

// getNetherlandsBBAN retrieves BBAN structure from Netherlands IBAN
func getNetherlandsBBAN(iban string) (BBAN, error) {
	if len(iban) != 18 {
		return BBAN{}, &ErrValidationLength{Expected: 18, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:18], BankCode: iban[4:8], BranchCode: "", AccountNumber: iban[8:18]}, nil
}
