// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateBelgiumIBAN validates Belgium IBAN
func validateBelgiumIBAN(iban string) error {
	if len(iban) != 16 {
		return &ErrValidationLength{Expected: 16, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "BE" {
		return &ErrValidationStaticValue{Position: 0, Expected: "BE", Actual: subject}
	}
	if subject := iban[2:16]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 14, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateBelgiumIBAN generates Belgium IBAN
func generateBelgiumIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("BE")
	ascii.Digits(sb, 14)
	return ReplaceChecksum(sb.String())
}
// getBelgiumBBAN retrieves BBAN structure from Belgium IBAN
func getBelgiumBBAN(iban string) (BBAN, error) {
	if len(iban) != 16 {
		return BBAN{}, &ErrValidationLength{Expected: 16, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:16], BankCode: iban[4:7], BranchCode: "", NationalChecksum: iban[14:16], AccountNumber: iban[7:14]}, nil
}
