// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateMongoliaIBAN validates Mongolia IBAN
func validateMongoliaIBAN(iban string) error {
	if len(iban) != 20 {
		return &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "MN" {
		return &ErrValidationStaticValue{Position: 0, Expected: "MN", Actual: subject}
	}
	if subject := iban[2:20]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 18, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateMongoliaIBAN generates Mongolia IBAN
func generateMongoliaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("MN")
	ascii.Digits(sb, 18)
	return ReplaceChecksum(sb.String())
}
// getMongoliaBBAN retrieves BBAN structure from Mongolia IBAN
func getMongoliaBBAN(iban string) (BBAN, error) {
	if len(iban) != 20 {
		return BBAN{}, &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:20], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:20]}, nil
}
