// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateLatviaIBAN validates Latvia IBAN
func validateLatviaIBAN(iban string) error {
	if len(iban) != 21 {
		return &ErrValidationLength{Expected: 21, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "LV" {
		return &ErrValidationStaticValue{Position: 0, Expected: "LV", Actual: subject}
	}
	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 2, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return &ErrValidationRange{Position: 4, Length: 4, Expected: CharacterTypeUpperCase, Actual: subject}
	}
	if subject := iban[8:21]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 8, Length: 13, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateLatviaIBAN generates Latvia IBAN
func generateLatviaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("LV")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.AlphaNumeric(sb, 13)
	return ReplaceChecksum(sb.String())
}
// getLatviaBBAN retrieves BBAN structure from Latvia IBAN
func getLatviaBBAN(iban string) (BBAN, error) {
	if len(iban) != 21 {
		return BBAN{}, &ErrValidationLength{Expected: 21, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:21], BankCode: iban[4:8], BranchCode: "", NationalChecksum: "", AccountNumber: iban[8:21]}, nil
}
