// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateCzechRepublicIBAN validates Czech Republic IBAN
func validateCzechRepublicIBAN(iban string) error {
	if len(iban) != 24 {
		return &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "CZ" {
		return &ErrValidationStaticValue{Position: 0, Expected: "CZ", Actual: subject}
	}
	if subject := iban[2:24]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 22, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateCzechRepublicIBAN generates Czech Republic IBAN
func generateCzechRepublicIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("CZ")
	ascii.Digits(sb, 22)
	return ReplaceChecksum(sb.String())
}
// getCzechRepublicBBAN retrieves BBAN structure from Czech Republic IBAN
func getCzechRepublicBBAN(iban string) (BBAN, error) {
	if len(iban) != 24 {
		return BBAN{}, &ErrValidationLength{Expected: 24, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:24], BankCode: iban[4:8], BranchCode: iban[8:14], NationalChecksum: "", AccountNumber: iban[14:24]}, nil
}
