// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"fmt"
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateMaltaIBAN validates Malta IBAN
func validateMaltaIBAN(iban string) error {
	if len(iban) != 31 {
		return fmt.Errorf("unexpected length, want: 31: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "MT" {
		return fmt.Errorf("static value rule, pos: 0, expected value: MT, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:4]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 2, length: 2, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[4:8]; !ascii.IsUpperCase(subject) {
		return fmt.Errorf("range rule, start pos: 4, length: 4, expected type UpperCaseLetters, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[8:13]; !ascii.IsDigit(subject) {
		return fmt.Errorf("range rule, start pos: 8, length: 5, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[13:31]; !ascii.IsAlphaNumeric(subject) {
		return fmt.Errorf("range rule, start pos: 13, length: 18, expected type AlphaNumeric, found %s: %w", subject, ErrValidation)
	}

	if c := checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// generateMaltaIBAN generates Malta IBAN
func generateMaltaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("MT")
	ascii.Digits(sb, 2)
	ascii.UpperCaseLetters(sb, 4)
	ascii.Digits(sb, 5)
	ascii.AlphaNumeric(sb, 18)

	return ReplaceChecksum(sb.String())
}

// getMaltaBBAN retrieves BBAN structure from Malta IBAN
func getMaltaBBAN(iban string) (BBAN, error) {
	if len(iban) != 31 {
		return BBAN{}, fmt.Errorf("unexpected length, want: 31: %w", ErrValidation)
	}

	return BBAN{
		BBAN:             iban[4:31],
		BankCode:         iban[4:8],
		BranchCode:       iban[8:13],
		NationalChecksum: "",
		AccountNumber:    iban[13:31],
	}, nil
}
