// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateOmanIBAN validates Oman IBAN
func validateOmanIBAN(iban string) error {
	if len(iban) != 23 {
		return &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "OM" {
		return &ErrValidationStaticValue{Position: 0, Expected: "OM", Actual: subject}
	}
	if subject := iban[2:7]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 5, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[7:23]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 7, Length: 16, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateOmanIBAN generates Oman IBAN
func generateOmanIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("OM")
	ascii.Digits(sb, 5)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getOmanBBAN retrieves BBAN structure from Oman IBAN
func getOmanBBAN(iban string) (BBAN, error) {
	if len(iban) != 23 {
		return BBAN{}, &ErrValidationLength{Expected: 23, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:23], BankCode: iban[4:7], BranchCode: "", AccountNumber: iban[7:23]}, nil
}
