// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateBosniaandHerzegovinaIBAN validates Bosnia and Herzegovina IBAN
func validateBosniaandHerzegovinaIBAN(iban string) error {
	if len(iban) != 20 {
		return &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "BA" {
		return &ErrValidationStaticValue{Position: 0, Expected: "BA", Actual: subject}
	}
	if subject := iban[2:20]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 18, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateBosniaandHerzegovinaIBAN generates Bosnia and Herzegovina IBAN
func generateBosniaandHerzegovinaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("BA")
	ascii.Digits(sb, 18)
	return ReplaceChecksum(sb.String())
}

// getBosniaandHerzegovinaBBAN retrieves BBAN structure from Bosnia and Herzegovina IBAN
func getBosniaandHerzegovinaBBAN(iban string) (BBAN, error) {
	if len(iban) != 20 {
		return BBAN{}, &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:20], BankCode: iban[4:7], BranchCode: iban[7:10], AccountNumber: iban[10:20]}, nil
}
