// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// validateGreeceIBAN validates Greece IBAN
func validateGreeceIBAN(iban string) error {
	if len(iban) != 27 {
		return &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "GR" {
		return &ErrValidationStaticValue{Position: 0, Expected: "GR", Actual: subject}
	}
	if subject := iban[2:11]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 9, Expected: CharacterTypeDigit, Actual: subject}
	}
	if subject := iban[11:27]; !ascii.IsAlphaNumeric(subject) {
		return &ErrValidationRange{Position: 11, Length: 16, Expected: CharacterTypeAlphaNumeric, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}

// generateGreeceIBAN generates Greece IBAN
func generateGreeceIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("GR")
	ascii.Digits(sb, 9)
	ascii.AlphaNumeric(sb, 16)
	return ReplaceChecksum(sb.String())
}

// getGreeceBBAN retrieves BBAN structure from Greece IBAN
func getGreeceBBAN(iban string) (BBAN, error) {
	if len(iban) != 27 {
		return BBAN{}, &ErrValidationLength{Expected: 27, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:27], BankCode: iban[4:7], BranchCode: iban[7:11], AccountNumber: iban[11:27]}, nil
}
