// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateEstoniaIBAN validates Estonia IBAN
func validateEstoniaIBAN(iban string) error {
	if len(iban) != 20 {
		return &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "EE" {
		return &ErrValidationStaticValue{Position: 0, Expected: "EE", Actual: subject}
	}
	if subject := iban[2:20]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 18, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateEstoniaIBAN generates Estonia IBAN
func generateEstoniaIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("EE")
	ascii.Digits(sb, 18)
	return ReplaceChecksum(sb.String())
}
// getEstoniaBBAN retrieves BBAN structure from Estonia IBAN
func getEstoniaBBAN(iban string) (BBAN, error) {
	if len(iban) != 20 {
		return BBAN{}, &ErrValidationLength{Expected: 20, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:20], BankCode: iban[4:6], BranchCode: "", NationalChecksum: iban[19:20], AccountNumber: iban[6:19]}, nil
}
