// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"
	"strings"

	"github.com/jacoelho/banking/ascii"
)

// ValidateRepublicOfKosovoIBAN validates Republic Of Kosovo IBAN
func ValidateRepublicOfKosovoIBAN(iban string) error {
	if len(iban) != 20 {
		return fmt.Errorf("unexpected length, want: 20: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "XK" {
		return fmt.Errorf("static value rule, pos: 0, expected value: XK, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:20]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 18, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateRepublicOfKosovoIBAN generates Republic Of Kosovo IBAN
func GenerateRepublicOfKosovoIBAN() string {
	var sb = new(strings.Builder)

	sb.WriteString("XK")
	generator.Digits(sb, 18)

	return ReplaceChecksum(sb.String())
}
