// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"

	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// ValidateNorwayIBAN validates Norway IBAN
func ValidateNorwayIBAN(iban string) error {
	if len(iban) != 15 {
		return fmt.Errorf("unexpected length, want: 15: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "NO" {
		return fmt.Errorf("static value rule, pos: 0, expected value: NO, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:15]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 13, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateNorwayIBAN generates Norway IBAN
func GenerateNorwayIBAN() string {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("NO")
	generator.Digits(sb, 13)

	return ReplaceChecksum(sb.String())
}
