// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"

	"github.com/jacoelho/banking/ascii"
	"github.com/jacoelho/banking/pool"
)

// ValidateSloveniaIBAN validates Slovenia IBAN
func ValidateSloveniaIBAN(iban string) error {
	if len(iban) != 19 {
		return fmt.Errorf("unexpected length, want: 19: %w", ErrValidation)
	}

	if subject := iban[0:2]; subject != "SI" {
		return fmt.Errorf("static value rule, pos: 0, expected value: SI, found %s: %w", subject, ErrValidation)
	}

	if subject := iban[2:19]; !ascii.Every(subject, ascii.IsDigit) {
		return fmt.Errorf("range rule, start pos: 2, length: 17, expected type Digit, found %s: %w", subject, ErrValidation)
	}

	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

	return nil
}

// GenerateSloveniaIBAN generates Slovenia IBAN
func GenerateSloveniaIBAN() string {
	sb := pool.BytesPool.Get()
	defer sb.Free()

	sb.WriteString("SI")
	generator.Digits(sb, 17)

	return ReplaceChecksum(sb.String())
}
