// Code generated by banking/registry; DO NOT EDIT.

package iban

import (
	"github.com/jacoelho/banking/pool"
	"github.com/jacoelho/banking/ascii"
)
// validateEgyptIBAN validates Egypt IBAN
func validateEgyptIBAN(iban string) error {
	if len(iban) != 29 {
		return &ErrValidationLength{Expected: 29, Actual: len(iban)}
	}
	if subject := iban[0:2]; subject != "EG" {
		return &ErrValidationStaticValue{Position: 0, Expected: "EG", Actual: subject}
	}
	if subject := iban[2:29]; !ascii.IsDigit(subject) {
		return &ErrValidationRange{Position: 2, Length: 27, Expected: CharacterTypeDigit, Actual: subject}
	}
	if c := checksum(iban); c != iban[2:4] {
		return &ErrValidationChecksum{Expected: c, Actual: iban[2:4]}
	}
	return nil
}
// generateEgyptIBAN generates Egypt IBAN
func generateEgyptIBAN() (string, error) {
	sb := pool.BytesPool.Get()
	defer sb.Free()
	sb.WriteString("EG")
	ascii.Digits(sb, 27)
	return ReplaceChecksum(sb.String())
}
// getEgyptBBAN retrieves BBAN structure from Egypt IBAN
func getEgyptBBAN(iban string) (BBAN, error) {
	if len(iban) != 29 {
		return BBAN{}, &ErrValidationLength{Expected: 29, Actual: len(iban)}
	}
	return BBAN{BBAN: iban[4:29], BankCode: iban[4:8], BranchCode: iban[8:12], NationalChecksum: "", AccountNumber: iban[12:29]}, nil
}
