// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"
)

// Generate IBAN based on ISO 3166-1 country code
func Generate(countryCode string) (string, error) {
	var result string

	switch countryCode {
	case al:
		result = generateAlbaniaIBAN()
	case ad:
		result = generateAndorraIBAN()
	case at:
		result = generateAustriaIBAN()
	case az:
		result = generateRepublicOfAzerbaijanIBAN()
	case bh:
		result = generateKingdomOfBahrainIBAN()
	case be:
		result = generateBelgiumIBAN()
	case ba:
		result = generateBosniaAndHerzegovinaIBAN()
	case br:
		result = generateBrazilIBAN()
	case bg:
		result = generateBulgariaIBAN()
	case cr:
		result = generateCostaRicaIBAN()
	case hr:
		result = generateCroatiaIBAN()
	case cy:
		result = generateCyprusIBAN()
	case cz:
		result = generateCzechRepublicIBAN()
	case dk:
		result = generateDenmarkIBAN()
	case fo:
		result = generateFaroeIslandsIBAN()
	case gl:
		result = generateGreenlandIBAN()
	case do:
		result = generateDominicanRepublicIBAN()
	case ee:
		result = generateEstoniaIBAN()
	case fi:
		result = generateFinlandIBAN()
	case fr:
		result = generateFranceIBAN()
	case gf:
		result = generateFrenchGuyanaIBAN()
	case gp:
		result = generateGuadeloupeIBAN()
	case mq:
		result = generateMartiniqueIBAN()
	case re:
		result = generateReunionIBAN()
	case fp:
		result = generateFrenchPolynesiaIBAN()
	case tf:
		result = generateFrenchSouthernTerritoriesIBAN()
	case yt:
		result = generateMayotteIBAN()
	case nc:
		result = generateNewCaledoniaIBAN()
	case bl:
		result = generateSaintBarthelemyIBAN()
	case mf:
		result = generateSaintMartinIBAN()
	case pm:
		result = generateSaintPierreEtMiquelonIBAN()
	case wf:
		result = generateWallisAndFutunaIslandsIBAN()
	case ge:
		result = generateGeorgiaIBAN()
	case de:
		result = generateGermanyIBAN()
	case gi:
		result = generateGibraltarIBAN()
	case gr:
		result = generateGreeceIBAN()
	case gt:
		result = generateGuatemalaIBAN()
	case hu:
		result = generateHungaryIBAN()
	case is:
		result = generateIcelandIBAN()
	case ie:
		result = generateIrelandIBAN()
	case il:
		result = generateIsraelIBAN()
	case it:
		result = generateItalyIBAN()
	case jo:
		result = generateJordanIBAN()
	case kz:
		result = generateKazakhstanIBAN()
	case xk:
		result = generateRepublicOfKosovoIBAN()
	case kw:
		result = generateKuwaitIBAN()
	case lv:
		result = generateLatviaIBAN()
	case lb:
		result = generateLebanonIBAN()
	case li:
		result = generatePrincipalityOfLiechtensteinIBAN()
	case lt:
		result = generateLithuaniaIBAN()
	case lu:
		result = generateLuxembourgIBAN()
	case mk:
		result = generateMacedoniaIBAN()
	case mt:
		result = generateMaltaIBAN()
	case mr:
		result = generateMauritaniaIBAN()
	case mu:
		result = generateMauritiusIBAN()
	case md:
		result = generateMoldovaIBAN()
	case mc:
		result = generateMonacoIBAN()
	case me:
		result = generateMontenegroIBAN()
	case nl:
		result = generateTheNetherlandsIBAN()
	case no:
		result = generateNorwayIBAN()
	case pk:
		result = generatePakistanIBAN()
	case ps:
		result = generateStateOfPalestineIBAN()
	case pl:
		result = generatePolandIBAN()
	case pt:
		result = generatePortugalIBAN()
	case qa:
		result = generateQatarIBAN()
	case ro:
		result = generateRomaniaIBAN()
	case lc:
		result = generateSaintLuciaIBAN()
	case sm:
		result = generateSanMarinoIBAN()
	case st:
		result = generateSaoTomeAndPrincipeIBAN()
	case sa:
		result = generateSaudiArabiaIBAN()
	case rs:
		result = generateSerbiaIBAN()
	case sk:
		result = generateSlovakRepublicIBAN()
	case si:
		result = generateSloveniaIBAN()
	case es:
		result = generateSpainIBAN()
	case se:
		result = generateSwedenIBAN()
	case ch:
		result = generateSwitzerlandIBAN()
	case tl:
		result = generateTimorLesteIBAN()
	case tn:
		result = generateTunisiaIBAN()
	case tr:
		result = generateTurkeyIBAN()
	case ae:
		result = generateUnitedArabEmiratesIBAN()
	case gb:
		result = generateUnitedKingdomIBAN()
	case vg:
		result = generateBritishVirginIslandsIBAN()
	case sc:
		result = generateSeychellesIBAN()
	case ua:
		result = generateUkraineIBAN()

	default:
		return "", fmt.Errorf("%s is not supported: %w", countryCode, ErrValidation)
	}

	return result, nil
}
