// Code generated by banking/registry; DO NOT EDIT.

package iban

import "fmt"

// IsSEPACountryCode returns if a country code is a SEPA member
func IsSEPACountryCode(countryCode string) (bool, error) {
	if len(countryCode) != 2 {
		return false, fmt.Errorf("unexpected country code length: %w", ErrValidation)
	}
	switch countryCode {
	case "AD":
		return true, nil
	case "AE":
		return false, nil
	case "AL":
		return false, nil
	case "AT":
		return true, nil
	case "AZ":
		return false, nil
	case "BA":
		return false, nil
	case "BE":
		return true, nil
	case "BG":
		return true, nil
	case "BH":
		return false, nil
	case "BI":
		return false, nil
	case "BR":
		return false, nil
	case "BY":
		return false, nil
	case "CH":
		return true, nil
	case "CR":
		return false, nil
	case "CY":
		return true, nil
	case "CZ":
		return true, nil
	case "DE":
		return true, nil
	case "DJ":
		return false, nil
	case "DK":
		return true, nil
	case "DO":
		return false, nil
	case "EE":
		return true, nil
	case "EG":
		return false, nil
	case "ES":
		return true, nil
	case "FI":
		return true, nil
	case "FK":
		return false, nil
	case "FO":
		return false, nil
	case "FR":
		return true, nil
	case "GB":
		return true, nil
	case "GE":
		return false, nil
	case "GI":
		return true, nil
	case "GL":
		return false, nil
	case "GR":
		return true, nil
	case "GT":
		return false, nil
	case "HN":
		return false, nil
	case "HR":
		return true, nil
	case "HU":
		return true, nil
	case "IE":
		return true, nil
	case "IL":
		return false, nil
	case "IQ":
		return false, nil
	case "IS":
		return true, nil
	case "IT":
		return true, nil
	case "JO":
		return false, nil
	case "KW":
		return false, nil
	case "KZ":
		return false, nil
	case "LB":
		return false, nil
	case "LC":
		return false, nil
	case "LI":
		return true, nil
	case "LT":
		return true, nil
	case "LU":
		return true, nil
	case "LV":
		return true, nil
	case "LY":
		return false, nil
	case "MC":
		return true, nil
	case "MD":
		return false, nil
	case "ME":
		return false, nil
	case "MK":
		return false, nil
	case "MN":
		return false, nil
	case "MR":
		return false, nil
	case "MT":
		return true, nil
	case "MU":
		return false, nil
	case "NI":
		return false, nil
	case "NL":
		return true, nil
	case "NO":
		return true, nil
	case "OM":
		return false, nil
	case "PK":
		return false, nil
	case "PL":
		return true, nil
	case "PS":
		return false, nil
	case "PT":
		return true, nil
	case "QA":
		return false, nil
	case "RO":
		return true, nil
	case "RS":
		return false, nil
	case "RU":
		return false, nil
	case "SA":
		return false, nil
	case "SC":
		return false, nil
	case "SD":
		return false, nil
	case "SE":
		return true, nil
	case "SI":
		return true, nil
	case "SK":
		return true, nil
	case "SM":
		return true, nil
	case "SO":
		return false, nil
	case "ST":
		return false, nil
	case "SV":
		return false, nil
	case "TL":
		return false, nil
	case "TN":
		return false, nil
	case "TR":
		return false, nil
	case "UA":
		return false, nil
	case "VA":
		return true, nil
	case "VG":
		return false, nil
	case "XK":
		return false, nil
	case "GF":
		return true, nil
	case "GP":
		return true, nil
	case "MQ":
		return true, nil
	case "RE":
		return true, nil
	case "FP":
		return false, nil
	case "TF":
		return false, nil
	case "YT":
		return true, nil
	case "NC":
		return false, nil
	case "BL":
		return true, nil
	case "MF":
		return true, nil
	case "PM":
		return false, nil
	case "WF":
		return false, nil
	case "YE":
		return false, nil
	default:
		return false, fmt.Errorf("%s is not supported: %w", countryCode, ErrValidation)
	}
}
func IsSEPA(iban string) (bool, error) {
	if len(iban) < 2 {
		return false, fmt.Errorf("unexpected iban length: %w", ErrValidation)
	}
	return IsSEPACountryCode(iban[0:2])
}
