// Code generated by banking/generator; DO NOT EDIT.

package iban

import (
	"fmt"
)

// Validate an IBAN
func Validate(iban string) error {
	if len(iban) < 2 {
		return fmt.Errorf("unexpected iban length: %w", ErrValidation)
	}

	code := iban[0:2]
	switch code {
	case al:
		return validateAlbaniaIBAN(iban)
	case ad:
		return validateAndorraIBAN(iban)
	case at:
		return validateAustriaIBAN(iban)
	case az:
		return validateRepublicOfAzerbaijanIBAN(iban)
	case bh:
		return validateKingdomOfBahrainIBAN(iban)
	case be:
		return validateBelgiumIBAN(iban)
	case ba:
		return validateBosniaAndHerzegovinaIBAN(iban)
	case br:
		return validateBrazilIBAN(iban)
	case bg:
		return validateBulgariaIBAN(iban)
	case cr:
		return validateCostaRicaIBAN(iban)
	case hr:
		return validateCroatiaIBAN(iban)
	case cy:
		return validateCyprusIBAN(iban)
	case cz:
		return validateCzechRepublicIBAN(iban)
	case dk:
		return validateDenmarkIBAN(iban)
	case fo:
		return validateFaroeIslandsIBAN(iban)
	case gl:
		return validateGreenlandIBAN(iban)
	case do:
		return validateDominicanRepublicIBAN(iban)
	case ee:
		return validateEstoniaIBAN(iban)
	case fi:
		return validateFinlandIBAN(iban)
	case fr:
		return validateFranceIBAN(iban)
	case gf:
		return validateFrenchGuyanaIBAN(iban)
	case gp:
		return validateGuadeloupeIBAN(iban)
	case mq:
		return validateMartiniqueIBAN(iban)
	case re:
		return validateReunionIBAN(iban)
	case fp:
		return validateFrenchPolynesiaIBAN(iban)
	case tf:
		return validateFrenchSouthernTerritoriesIBAN(iban)
	case yt:
		return validateMayotteIBAN(iban)
	case nc:
		return validateNewCaledoniaIBAN(iban)
	case bl:
		return validateSaintBarthelemyIBAN(iban)
	case mf:
		return validateSaintMartinIBAN(iban)
	case pm:
		return validateSaintPierreEtMiquelonIBAN(iban)
	case wf:
		return validateWallisAndFutunaIslandsIBAN(iban)
	case ge:
		return validateGeorgiaIBAN(iban)
	case de:
		return validateGermanyIBAN(iban)
	case gi:
		return validateGibraltarIBAN(iban)
	case gr:
		return validateGreeceIBAN(iban)
	case gt:
		return validateGuatemalaIBAN(iban)
	case hu:
		return validateHungaryIBAN(iban)
	case is:
		return validateIcelandIBAN(iban)
	case ie:
		return validateIrelandIBAN(iban)
	case il:
		return validateIsraelIBAN(iban)
	case it:
		return validateItalyIBAN(iban)
	case jo:
		return validateJordanIBAN(iban)
	case kz:
		return validateKazakhstanIBAN(iban)
	case xk:
		return validateRepublicOfKosovoIBAN(iban)
	case kw:
		return validateKuwaitIBAN(iban)
	case lv:
		return validateLatviaIBAN(iban)
	case lb:
		return validateLebanonIBAN(iban)
	case li:
		return validatePrincipalityOfLiechtensteinIBAN(iban)
	case lt:
		return validateLithuaniaIBAN(iban)
	case lu:
		return validateLuxembourgIBAN(iban)
	case mk:
		return validateMacedoniaIBAN(iban)
	case mt:
		return validateMaltaIBAN(iban)
	case mr:
		return validateMauritaniaIBAN(iban)
	case mu:
		return validateMauritiusIBAN(iban)
	case md:
		return validateMoldovaIBAN(iban)
	case mc:
		return validateMonacoIBAN(iban)
	case me:
		return validateMontenegroIBAN(iban)
	case nl:
		return validateTheNetherlandsIBAN(iban)
	case no:
		return validateNorwayIBAN(iban)
	case pk:
		return validatePakistanIBAN(iban)
	case ps:
		return validateStateOfPalestineIBAN(iban)
	case pl:
		return validatePolandIBAN(iban)
	case pt:
		return validatePortugalIBAN(iban)
	case qa:
		return validateQatarIBAN(iban)
	case ro:
		return validateRomaniaIBAN(iban)
	case lc:
		return validateSaintLuciaIBAN(iban)
	case sm:
		return validateSanMarinoIBAN(iban)
	case st:
		return validateSaoTomeAndPrincipeIBAN(iban)
	case sa:
		return validateSaudiArabiaIBAN(iban)
	case rs:
		return validateSerbiaIBAN(iban)
	case sk:
		return validateSlovakRepublicIBAN(iban)
	case si:
		return validateSloveniaIBAN(iban)
	case es:
		return validateSpainIBAN(iban)
	case se:
		return validateSwedenIBAN(iban)
	case ch:
		return validateSwitzerlandIBAN(iban)
	case tl:
		return validateTimorLesteIBAN(iban)
	case tn:
		return validateTunisiaIBAN(iban)
	case tr:
		return validateTurkeyIBAN(iban)
	case ae:
		return validateUnitedArabEmiratesIBAN(iban)
	case gb:
		return validateUnitedKingdomIBAN(iban)
	case vg:
		return validateBritishVirginIslandsIBAN(iban)
	case sc:
		return validateSeychellesIBAN(iban)
	case ua:
		return validateUkraineIBAN(iban)

	default:
		return fmt.Errorf("%s is not supported: %w", code, ErrValidation)
	}
}
