// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

const _TokenType_name = "ILLEGALEOFWORDINTEGERSYMBOLBANG"

var _TokenType_index = [...]uint8{0, 7, 10, 14, 21, 27, 31}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
