package ibangen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/jacoelho/banking/internal/ibanregistry"
)

// Header is the first line written to files owned by this generator.
const Header = "// Code generated by cmd/banking-registry; DO NOT EDIT."

const registryDataFileName = "registry_data.go"

const (
	nonSEPACountry = 1
	sepaCountry    = 2
)

var generatedHeaders = map[string]bool{
	Header: true,
	"// Code generated by banking/registry; DO NOT EDIT.": true,
}

// Generate writes a complete generated IBAN package into dst.
func Generate(dst string, registry ibanregistry.Registry) error {
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	if err := requireGeneratedScope(dst); err != nil {
		return err
	}

	source, err := registryDataFile(registry)
	if err != nil {
		return err
	}
	if err := writeFormatted(filepath.Join(dst, registryDataFileName), source); err != nil {
		return fmt.Errorf("%s: %w", registryDataFileName, err)
	}
	return removeLegacyCountryFiles(dst)
}

func registryDataFile(registry ibanregistry.Registry) (string, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "%s\n\npackage iban\n\n", Header)
	if err := writeCountryCodeIndex(&b, registry.Countries); err != nil {
		return "", err
	}
	if err := writeCountrySEPAIndex(&b, registry.Countries); err != nil {
		return "", err
	}
	writeCountrySpecs(&b, registry.Countries)
	return b.String(), nil
}

func writeCountryCodeIndex(b *bytes.Buffer, countries []ibanregistry.CountrySpec) error {
	var index [26 * 26]uint16
	for i, country := range countries {
		slot, err := countryCodeSlot(country.Code)
		if err != nil {
			return fmt.Errorf("country %s: %w", country.Code, err)
		}
		if index[slot] != 0 {
			return fmt.Errorf("duplicate country code %q", country.Code)
		}
		if i+1 > int(^uint16(0)) {
			return fmt.Errorf("too many countries: %d", len(countries))
		}
		index[slot] = uint16(i + 1)
	}

	fmt.Fprintln(b, "var countryCodeIndex = [26 * 26]uint16{")
	for slot, value := range index {
		if value != 0 {
			fmt.Fprintf(b, "%d: %d,\n", slot, value)
		}
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	return nil
}

func writeCountrySEPAIndex(b *bytes.Buffer, countries []ibanregistry.CountrySpec) error {
	var index [26 * 26]uint8
	for _, country := range countries {
		slot, err := countryCodeSlot(country.Code)
		if err != nil {
			return fmt.Errorf("country %s: %w", country.Code, err)
		}
		if country.IsSEPA {
			index[slot] = sepaCountry
		} else {
			index[slot] = nonSEPACountry
		}
	}

	fmt.Fprintln(b, "var countrySEPAIndex = [26 * 26]uint8{")
	for slot, value := range index {
		if value != 0 {
			fmt.Fprintf(b, "%d: %s,\n", slot, sepaIndexValueLiteral(value))
		}
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	return nil
}

func sepaIndexValueLiteral(value uint8) string {
	switch value {
	case nonSEPACountry:
		return "nonSEPACountry"
	case sepaCountry:
		return "sepaCountry"
	default:
		panic("unknown SEPA index value")
	}
}

func countryCodeSlot(code string) (int, error) {
	if len(code) != 2 {
		return 0, fmt.Errorf("country code must be 2 bytes")
	}
	if code[0] < 'A' || code[0] > 'Z' || code[1] < 'A' || code[1] > 'Z' {
		return 0, fmt.Errorf("country code must be uppercase ASCII")
	}
	return int(code[0]-'A')*26 + int(code[1]-'A'), nil
}

func writeCountrySpecs(b *bytes.Buffer, countries []ibanregistry.CountrySpec) {
	fmt.Fprintln(b, "var countrySpecs = []countrySpec{")
	for _, country := range countries {
		fmt.Fprintln(b, "{")
		fmt.Fprintf(b, "code: %q,\n", country.Code)
		fmt.Fprintf(b, "length: %d,\n", country.IBAN.Length)
		fmt.Fprintln(b, "rules: []ibanRule{")
		for _, rule := range country.IBAN.Rules {
			fmt.Fprintf(b, "%s,\n", ibanRuleLiteral(rule))
		}
		fmt.Fprintln(b, "},")
		fmt.Fprintf(b, "bankCode: %s,\n", optionalSpanLiteral(country.BankCode))
		fmt.Fprintf(b, "branchCode: %s,\n", optionalSpanLiteral(country.BranchCode))
		fmt.Fprintf(b, "accountNumber: %s,\n", spanLiteral(country.AccountNumber))
		fmt.Fprintln(b, "},")
	}
	fmt.Fprintln(b, "}")
}

func ibanRuleLiteral(rule ibanregistry.Rule) string {
	switch r := rule.(type) {
	case ibanregistry.StaticRule:
		return fmt.Sprintf("{start: %d, length: %d, kind: ibanRuleStatic, value: %q}", r.StartPosition, len(r.Value), r.Value)
	case ibanregistry.RangeRule:
		return fmt.Sprintf("{start: %d, length: %d, kind: %s}", r.StartPosition, r.Length, ruleKindLiteral(r.Format))
	default:
		panic(fmt.Sprintf("unknown rule type %T", rule))
	}
}

func ruleKindLiteral(format ibanregistry.Format) string {
	switch format {
	case ibanregistry.Digit:
		return "ibanRuleDigit"
	case ibanregistry.UpperCaseLetters:
		return "ibanRuleUpperCase"
	case ibanregistry.AlphaNumeric:
		return "ibanRuleAlphaNumeric"
	default:
		panic("unknown range format")
	}
}

func optionalSpanLiteral(span ibanregistry.OptionalSpan) string {
	if !span.Present {
		return "bbanSpan{}"
	}
	return spanLiteral(span.Span)
}

func spanLiteral(span ibanregistry.Span) string {
	return fmt.Sprintf("bbanSpan{start: %d, end: %d, present: true}", span.Start, span.End)
}

func writeFormatted(path, source string) error {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("formatting generated source: %w\n%s", err, source)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func requireGeneratedScope(dst string) error {
	path := filepath.Join(dst, registryDataFileName)
	if _, statErr := os.Stat(path); statErr == nil {
		if headerErr := requireGeneratedHeader(path); headerErr != nil {
			return headerErr
		}
	} else if !os.IsNotExist(statErr) {
		return statErr
	}

	matches, err := filepath.Glob(filepath.Join(dst, "country_*.go"))
	if err != nil {
		return err
	}
	for _, path := range matches {
		if err := requireGeneratedHeader(path); err != nil {
			return err
		}
	}
	return nil
}

func removeLegacyCountryFiles(dst string) error {
	matches, err := filepath.Glob(filepath.Join(dst, "country_*.go"))
	if err != nil {
		return err
	}
	slices.Sort(matches)
	for _, path := range matches {
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return nil
}

func requireGeneratedHeader(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	first := string(data)
	if newline := strings.IndexByte(first, '\n'); newline >= 0 {
		first = first[:newline]
	}
	if !generatedHeaders[strings.TrimRight(first, "\r")] {
		return fmt.Errorf("%s is in generated file scope but does not have generated header", path)
	}
	return nil
}
