package generator

const validateCountryTmpl = `// Code generated by banking/generator; DO NOT EDIT.

package {{ .PackageName }}

import (
    "fmt"

    "github.com/jacoelho/banking/ascii"
)

func {{ .FunctionName }}(iban string) error {
    if len(iban) != {{ .Length }} {
        return fmt.Errorf("unexpected length, want: {{ .Length }}: %w", ErrValidation)
    }
    {{ range .Rules }}
    if subject := iban[{{ .StartPos }}:{{ .EndPos }}]; {{ rule . "subject" }} {
        return fmt.Errorf("{{ .String }}, found %s: %w", subject, ErrValidation)
    }
    {{ end }}
	if c := Checksum(iban); c != iban[2:4] {
		return fmt.Errorf("incorrect checksum: %w", ErrValidation)
	}

    return nil
}
`

const validateTmpl = `// Code generated by banking/generator; DO NOT EDIT.

package {{ .PackageName }}

import (
    "fmt"
)

func Validate(iban string) error {
    if len(iban) < 2 {
        return fmt.Errorf("unexpected length: %w", ErrValidation)
    }
	
	code := iban[0:2]
	switch code {
    {{- range .Functions }}
    case "{{ .Code }}":
		return {{ .Fn }}(iban)
    {{ end -}}
	default:
		return fmt.Errorf("%s is not supported: %w", code, ErrValidation)
	}
}
`
