on:
  schedule:
    - cron: "0 0 */3 * *"

name: Check for registry changes

permissions:
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      - name: Fetch registry
        run: |
          curl --fail -Ls -b cookies.txt -o registry.pdf \
          'https://www.swift.com/resource/iban-registry-pdf' \
          -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:135.0) Gecko/20100101 Firefox/135.0' \
          -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
          -H 'Accept-Language: en-GB,en;q=0.5' \
          -H 'Accept-Encoding: gzip, deflate, br, zstd' \
          -H 'Referer: https://www.google.com/' \
          -H 'Upgrade-Insecure-Requests: 1' \
          -H 'Sec-Fetch-Dest: document' \
          -H 'Sec-Fetch-Mode: navigate' \
          -H 'Sec-Fetch-Site: cross-site' \
          -H 'Sec-Fetch-User: ?1' \
          -H 'Connection: keep-alive' \
          -H 'Priority: u=0, i' \
          -H 'Pragma: no-cache' \
          -H 'Cache-Control: no-cache'

      - name: Cache hash
        id: cache
        uses: actions/cache@v3
        with:
          path: registry.pdf
          key: ${{ hashFiles('registry.pdf') }}

      - name: Create issue
        if: steps.cache.outputs.cache-hit != 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
