on:
  schedule:
    - cron: "0 0 */3 * *"

name: Check for registry changes

permissions:
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      - name: Fetch registry
        run: |
          curl --fail -Ls \
          -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0' \
          -H 'Accept: */*' \
          -H 'Accept-Language: en-GB,en;q=0.5' \
          -H 'Accept-Encoding: gzip, deflate, br, zstd' \
          -H 'Connection: keep-alive' \
          -H 'Referer: https://www.google.com' \
          -H 'Sec-Fetch-Dest: script' \
          -H 'Sec-Fetch-Mode: no-cors' \
          -H 'Sec-Fetch-Site: same-origin' \
          -H 'Pragma: no-cache' \
          -H 'Cache-Control: no-cache' \
          -H 'TE: trailers' \
          https://www.swift.com/node/9606 -o registry.pdf

      - name: Cache hash
        id: cache
        uses: actions/cache@v3
        with:
          path: registry.pdf
          key: ${{ hashFiles('registry.pdf') }}

      - name: Create issue
        if: steps.cache.outputs.cache-hit != 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
